AllCops:
  Exclude:
    - 'app/views/**/*'
    - 'bin/**/*'
    - 'db/schema.rb'
    - 'db/migrate/*.rb'
  Include:
    - rubocop-rspec
  DisplayCopNames: true
  TargetRubyVersion: 2.3
Rails:
  Enabled: true
Style/Documentation:
  Enabled: false
Metrics/LineLength:
  Enabled: false
Rails/HasAndBelongsToMany:
  Enabled: false
Metrics/AbcSize:
  Max: 20
